Content-Type: text/html

<html>
<head>
<title>Test POST Data</title>
</head>
<body>
<h1>Received POST Data</h1>
<p><strong>age:</strong> 26</p>
<p><strong>city:</strong> benguerir</p>
<p><strong>name:</strong> ayoub</p>
<!--: spam
Content-Type: text/html

<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> -->
<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> --> -->
</font> </font> </font> </script> </object> </blockquote> </pre>
</table> </table> </table> </table> </table> </font> </font> </font><body bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>AttributeError</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 3.9.6: /Library/Developer/CommandLineTools/usr/bin/python3<br>Wed May 28 13:59:38 2025</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///Users/aezzahir/Dev/webserv/www/cgi-bin/test_post.py">/Users/aezzahir/Dev/webserv/www/cgi-bin/test_post.py</a> in <strong>&lt;module&gt;</strong></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;35</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;existing_data&nbsp;=&nbsp;json.load(json_file)<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;36</small>&nbsp;#&nbsp;Append&nbsp;the&nbsp;new&nbsp;data&nbsp;to&nbsp;the&nbsp;existing&nbsp;data<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;37</small>&nbsp;existing_data.append(data)<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;38</small>&nbsp;#&nbsp;Write&nbsp;the&nbsp;updated&nbsp;data&nbsp;back&nbsp;to&nbsp;the&nbsp;JSON&nbsp;file<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;39</small>&nbsp;with&nbsp;open(json_file_path,&nbsp;'w')&nbsp;as&nbsp;json_file:<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090"><strong>existing_data</strong>&nbsp;= {'email': None, 'name': 'ayoub'}, existing_data.append <em>undefined</em>, <strong>data</strong>&nbsp;= {'age': '26', 'city': 'benguerir', 'name': 'ayoub'}</font></small></td></tr></table><p><strong>AttributeError</strong>: 'dict' object has no attribute 'append'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
("'dict' object has no attribute 'append'",)
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>with_traceback&nbsp;=
&lt;built-in method with_traceback of AttributeError object&gt;


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "/Users/aezzahir/Dev/webserv/www/cgi-bin/test_post.py", line 37, in &lt;module&gt;
    existing_data.append(data)
AttributeError: 'dict' object has no attribute 'append'

-->


